"""
report_generator.py
-------------------
Generates a structured forensic text report summarizing all analysis
results, detected anomalies, confidence score, and legal references.
"""

from datetime import datetime


def generate_text_report(
    image_filename: str,
    confidence_score: float,
    verdict: str,
    findings: list[str],
    ssim_score: float | None = None,
    ocr_data: dict | None = None,
    mode: str = 'single',
) -> str:
    """
    Build a comprehensive forensic report as a plain-text string.

    Args:
        image_filename:   Name(s) of uploaded file(s).
        confidence_score: Calculated manipulation confidence (0–100).
        verdict:          Final verdict string.
        findings:         List of finding statements.
        ssim_score:       SSIM score (comparison mode only).
        ocr_data:         OCR results dict.
        mode:             'single' or 'compare'.

    Returns:
        A formatted string suitable for download as a .txt file.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    mode_label = 'Single Image Analysis' if mode == 'single' else 'Dual-Image Comparison Analysis'

    divider = '=' * 80
    thin = '-' * 80

    report_lines = [
        divider,
        '        SCREENSHOT MANIPULATION DETECTION SYSTEM — FORENSIC REPORT',
        divider,
        '',
        f'Report Generated : {timestamp}',
        f'Analysis Mode    : {mode_label}',
        f'File(s)          : {image_filename}',
        '',
        thin,
        'EXECUTIVE SUMMARY',
        thin,
        '',
        f'  VERDICT          : {verdict}',
        f'  CONFIDENCE SCORE : {confidence_score:.1f}%',
        '',
    ]

    if ssim_score is not None:
        report_lines += [
            f'  SSIM SCORE       : {ssim_score:.4f}  '
            f'(1.0 = identical, < 0.95 = significant difference)',
            '',
        ]

    report_lines += [
        thin,
        'DETECTION FINDINGS',
        thin,
        '',
    ]

    if findings:
        for i, finding in enumerate(findings, 1):
            report_lines.append(f'  {i}. {finding}')
    else:
        report_lines.append('  No significant anomalies detected.')

    report_lines += [
        '',
        thin,
        'DETECTION TECHNIQUES APPLIED',
        thin,
        '',
        '  1. Image Preprocessing         — Resize, grayscale, normalization',
        '  2. Error Level Analysis (ELA)  — JPEG re-compression inconsistency detection',
        '  3. SSIM Comparison             — Structural similarity between image pairs',
        '  4. Pixel Difference Analysis   — Per-pixel comparison with heatmap generation',
        '  5. Noise Inconsistency Check   — Block-level noise variance analysis',
        '  6. Canny Edge Detection        — Identification of artificial edge boundaries',
        '  7. OCR (Tesseract)             — Text extraction and numeric anomaly detection',
        '',
    ]

    if ocr_data:
        full_text = ocr_data.get('full_text', '').strip()
        currency = ocr_data.get('currency_amounts', [])
        report_lines += [
            thin,
            'OCR TEXT EXTRACTION RESULTS',
            thin,
            '',
        ]
        if currency:
            report_lines.append(f'  Currency Amounts Found : {", ".join(currency)}')
            report_lines.append('')
        if full_text:
            report_lines.append('  Extracted Text:')
            for line in full_text.split('\n')[:30]:
                report_lines.append(f'    {line}')
        else:
            report_lines.append('  No readable text extracted.')
        report_lines.append('')

    report_lines += [
        thin,
        'LEGAL RELEVANCE',
        thin,
        '',
        '  Digital evidence manipulation may constitute an offence under:',
        '',
        '  1. INFORMATION TECHNOLOGY ACT, 2000',
        '     • Section 66C — Identity theft using a computer resource',
        '       Punishment: Imprisonment up to 3 years + fine up to ₹1,00,000',
        '     • Section 66D — Cheating by personation using a computer resource',
        '       Punishment: Imprisonment up to 3 years + fine up to ₹1,00,000',
        '',
        '  2. INDIAN EVIDENCE ACT, 1872',
        '     • Section 65B — Admissibility of electronic records',
        '       Electronic evidence must be certified and unaltered to be admissible.',
        '       A tampered document may be challenged and excluded from evidence.',
        '',
        '  3. INDIAN PENAL CODE (IPC)',
        '     • Section 463 — Forgery of documents',
        '     • Section 464 — Making a false document',
        '     • Section 468 — Forgery for the purpose of cheating',
        '',
        thin,
        'DISCLAIMER',
        thin,
        '',
        '  This report is generated by an automated forensic analysis tool for',
        '  educational and investigative purposes. Results must be reviewed by a',
        '  certified digital forensic expert before use in any legal proceeding.',
        '  This tool is designed to assist detection — not to replace expert judgment.',
        '',
        divider,
        '                             END OF REPORT',
        divider,
    ]

    return '\n'.join(report_lines)
